# Configurações de build para o Netlify
[build]
  # O diretório que será publicado. Como seus arquivos estão na raiz, usamos "."
  publish = "."

# Configuração do plugin de sitemap
[[plugins]]
  # Nome do pacote do plugin
  package = "@netlify/plugin-sitemap"

  [plugins.options]
    # URL base do seu site para gerar os links corretos no sitemap
    baseUrl = "https://cozinha-criativpromo.netlify.app"