[build]
  publish = "."       # mantém a raiz como diretório publicado
  # (não precisa de comando de build para site estático)

[[plugins]]
  package = "@netlify/plugin-sitemap"

    [plugins.inputs]   # <-- era "options"
    buildDir = "."     # garante que o sitemap seja salvo na pasta publicada
    # urlPrefix ou baseUrl são opcionais; o plugin usa o domínio da Netlify
